# Generated by Django 2.0.7 on 2018-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180726_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='hash_md5',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
