# Generated by Django 2.1.3 on 2018-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180827_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='available_disk_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='available_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
