# Generated by Django 2.1.3 on 2018-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181114_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='password',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
