# Generated by Django 2.1.3 on 2018-11-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181114_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='authtoken',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='registrationtoken',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='registrationtoken',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='resetpasswordtoken',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resetpasswordtoken',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='sshkey',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sshkey',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
