# Generated by Django 2.1.5 on 2019-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181222_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
