# Generated by Django 2.1.5 on 2019-02-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtoken',
            name='password',
        ),
    ]
