# Generated by Django 2.0.7 on 2018-07-25 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('include_all_sub_domains', models.BooleanField(default=False)),
                ('destination_ip', models.GenericIPAddressField()),
                ('destination_http_port', models.IntegerField(default=80)),
                ('destination_https_port', models.IntegerField(default=443)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReverseProxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('public_ipv4', models.GenericIPAddressField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='reverse_proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ReverseProxy'),
        ),
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
