# Generated by Django 2.0.7 on 2018-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20180725_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
