# Generated by Django 2.0.7 on 2018-07-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_domain_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='reverse_proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='network.ReverseProxy'),
        ),
    ]
