# Generated by Django 2.1.3 on 2018-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20180726_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='reverseproxy',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
