# Generated by Django 2.1.3 on 2018-11-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20181114_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='reverseproxy',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reverseproxy',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
