# Generated by Django 2.1.3 on 2018-11-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20181118_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='destination_ip',
            field=models.CharField(max_length=39, validators=[django.core.validators.validate_ipv46_address]),
        ),
        migrations.AlterField(
            model_name='reverseproxy',
            name='public_ipv4',
            field=models.CharField(max_length=39, validators=[django.core.validators.validate_ipv46_address]),
        ),
    ]
