# Generated by Django 2.1.5 on 2019-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_reverseproxy_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='deleted',
        ),
        migrations.AddField(
            model_name='domain',
            name='state',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('UPDATING', 'UPDATING'), ('ACTIVE', 'ACTIVE'), ('DELETING', 'DELETING')], db_index=True, default='CREATING', max_length=32),
        ),
    ]
