# Generated by Django 2.1.5 on 2019-02-02 18:01

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Domain = apps.get_model("network", "Domain")
    db_alias = schema_editor.connection.alias
    Domain.objects.using(db_alias).update(state='ACTIVE')


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20190202_1801'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
