# Generated by Django 2.1.5 on 2019-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20190202_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='event_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
