# Generated by Django 2.1.3 on 2018-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='backup_path',
        ),
    ]
