# Generated by Django 2.1.3 on 2018-11-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0003_auto_20181118_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerevent',
            name='metadata',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('STOPPING', 'STOPPING'), ('STOPPED', 'STOPPED'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('REBOOTING', 'REBOOTING'), ('DELETING', 'DELETING'), ('BACKING_UP', 'BACKING_UP'), ('RESTORING', 'RESTORING')], default='CREATING', max_length=16),
        ),
    ]
