# Generated by Django 2.1.3 on 2018-11-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0005_auto_20181119_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='endpoint',
        ),
    ]
