# Generated by Django 2.1.5 on 2019-02-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0006_remove_host_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='state',
            field=models.CharField(
                choices=[('CREATING', 'CREATING'), ('ACTIVE', 'ACTIVE'), ('DELETING', 'DELETING'), ('RESTORING', 'RESTORING')],
                db_index=True, default='CREATING', max_length=32),
        ),

    ]
