# Generated by Django 2.1.5 on 2019-02-02 17:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Backup = apps.get_model("compute", "Backup")
    db_alias = schema_editor.connection.alias
    Backup.objects.using(db_alias).update(state='ACTIVE')


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0007_backup_state'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
