# Generated by Django 2.1.7 on 2019-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0009_auto_20190202_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('UPDATING', 'UPDATING'), ('STOPPING', 'STOPPING'), ('STOPPED', 'STOPPED'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('REBOOTING', 'REBOOTING'), ('DELETING', 'DELETING'), ('BACKING_UP', 'BACKING_UP'), ('RESTORING', 'RESTORING'), ('RESIZING', 'RESIZING')], default='CREATING', max_length=16),
        ),
        migrations.AlterField(
            model_name='containerevent',
            name='type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('STOPPED', 'STOPPED'), ('REBOOTED', 'REBOOTED'), ('PASSWORD_RESET', 'PASSWORD_RESET'), ('BACKED_UP', 'BACKED_UP'), ('RESIZED', 'RESIZED'), ('UPDATED', 'UPDATED')], max_length=16),
        ),
    ]
