# Generated by Django 2.1.3 on 2018-12-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_auto_20181209_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_assigned_by_me', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
