# Generated by Django 2.1.3 on 2018-12-22 12:00

from django.db import migrations, models
import xplace.support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20181222_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(db_index=True, default=xplace.support.models.generate_ticket_code, max_length=16),
        ),
    ]
