# Generated by Django 2.1.3 on 2018-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN PROGRESS'), ('CLOSED', 'CLOSED')], db_index=True, default='OPEN', max_length=16),
        ),
    ]
