# Generated by Django 2.1.5 on 2019-01-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20181222_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at']},
        ),
    ]
