# Generated by Django 2.1.7 on 2019-03-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20190126_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
